name: CI

on:
  push:
    branches:
      - dev # Change this to your default branch
  pull_request:
    branches:
      - dev # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: acl
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=30s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Run tests
        run: |
          docker-compose up -d
          docker-compose exec app php artisan migrate --force
          docker-compose exec app php artisan test
          docker-compose down

      - name: Build assets
        run: |
          docker-compose up -d
          docker-compose exec app npm install
          docker-compose exec app npm run build
          docker-compose down
